In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import requests
import seaborn as sns
from io import StringIO
%matplotlib inline
import json
import glob
from fuzzywuzzy import fuzz
from pandas.io.json import json_normalize
#pd.set_option('display.max_columns', None,'display.max_rows', None)

In [2]:
Google_APIs=glob.glob(('data/google_places_results/*.json'))

In [3]:
df = pd.DataFrame()

In [4]:
for i in Google_APIs:
    df_new = pd.read_json(i)
    df = pd.concat([df,df_new])

In [5]:
df.tail(3)

,mapped_location,address,results
26,"(36.18837, -86.7676)","1001 Meridian St, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'..."
27,"(36.1458305, -86.8167581)","221 31st Ave N, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'..."
28,"(36.08778474206125, -86.72961779427743)","3806 Nolensville Pike, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'..."

In [6]:
df=df.reset_index(drop=True)

In [7]:
df.tail(3)

,mapped_location,address,results
4826,"(36.18837, -86.7676)","1001 Meridian St, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'..."
4827,"(36.1458305, -86.8167581)","221 31st Ave N, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'..."
4828,"(36.08778474206125, -86.72961779427743)","3806 Nolensville Pike, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'..."

In [8]:
df.head(3)

,mapped_location,address,results
0,"(36.0685457, -86.6838975)","2045 Antioch Pike, Antioch","[{'business_status': 'OPERATIONAL', 'geometry'..."
1,"(36.211269429469425, -86.6943024067459)","2800 Opryland Dr, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'..."
2,"(36.1235, -86.79013)","2607 12th Ave S, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'..."

In [9]:
df.iloc[0]['results'][0]

{'business_status': 'OPERATIONAL',
 'geometry': {'location': {'lat': 36.0685457, 'lng': -86.6838975},
  'viewport': {'northeast': {'lat': 36.06998608029151,
    'lng': -86.6823848697085},
   'southwest': {'lat': 36.06728811970851, 'lng': -86.6850828302915}}},
 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png',
 'name': 'Los Paisanos',
 'opening_hours': {'open_now': True},
 'place_id': 'ChIJ7w-yGUFuZIgR7rrQpRfCGgw',
 'plus_code': {'compound_code': '3898+CC Nashville, TN, USA',
  'global_code': '868M3898+CC'},
 'rating': 4.2,
 'reference': 'ChIJ7w-yGUFuZIgR7rrQpRfCGgw',
 'scope': 'GOOGLE',
 'types': ['night_club', 'bar', 'point_of_interest', 'establishment'],
 'user_ratings_total': 6,
 'vicinity': '2045 Antioch Pike, Antioch'}

In [10]:
name1 = df.iloc[0]['results'][0]['name']
name1

'Los Paisanos'

In [11]:
vicinity1 = df.iloc[0]['results'][0]['vicinity']
vicinity1

'2045 Antioch Pike, Antioch'

In [12]:
types1 = df.iloc[0]['results'][0]['types']
types1

['night_club', 'bar', 'point_of_interest', 'establishment']

In [13]:
name1=[]
name2=[]
name3=[]
name4=[]
name5=[]

In [14]:
vicinity1=[]
vicinity2=[]
vicinity3=[]
vicinity4=[]
vicinity5=[]

In [15]:
type1=[]
type2=[]
type3=[]
type4=[]
type5=[]

In [16]:
for row in range (4829):
    for i in range (5):
        name = df.iloc[row]['results'][i]['name']
        vars()['name'+str(i+1)].append(name)
        
        vicinity = df.iloc[row]['results'][i]['vicinity']
        vars()['vicinity'+str(i+1)].append(vicinity)
             
        type = df.iloc[row]['results'][i]['types']
        vars()['type'+str(i+1)].append(type)

In [17]:
variable = pd.DataFrame(
    {'business_name1': name1,
     'business_vicinity1': vicinity1,
     'business_type1': type1,
     'business_name2': name2,
     'business_vicinity2': vicinity2,
     'business_type2': type2,
     'business_name3': name3,
     'business_vicinity3': vicinity3,
     'business_type3': type3,
     'business_name4': name4,
     'business_vicinity4': vicinity4,
     'business_type4': type4,
     'business_name5': name5,
     'business_vicinity5': vicinity5,
     'business_type5': type5,
     })

In [18]:
variable.tail()

,business_name1,business_vicinity1,business_type1,business_name2,business_vicinity2,business_type2,business_name3,business_vicinity3,business_type3,business_name4,business_vicinity4,business_type4,business_name5,business_vicinity5,business_type5
4824,Mid-Tenn Sheet Metal,"3638 Dickerson Pike, Nashville","[general_contractor, point_of_interest, establ...","Keith L. Snead Sr, DC","3638 Dickerson Pike, Nashville","[point_of_interest, establishment]",Bellshire Wellness Center,"3638 Dickerson Pike, Nashville","[health, point_of_interest, establishment]",Oldham Electric Co,"3638 Dickerson Pike STE 203, Nashville","[electrician, point_of_interest, establishment]",Dr. Speakers Network LLC,"3638 Dickerson Pike STE 203, Nashville","[health, point_of_interest, establishment]"
4825,Golden Coast,"1722 West End Avenue, Nashville","[restaurant, food, point_of_interest, establis...",Shabu-Shabu,"1722 West End Avenue, Nashville","[restaurant, food, point_of_interest, establis...",West End Ave & 18th Ave N WB,United States,"[transit_station, point_of_interest, establish...",Beacon Hill Staffing Group,"1720 West End Avenue Suite 250, Nashville","[point_of_interest, establishment]",Pinaire Roofing,"1720 West End Avenue #530, Nashville","[roofing_contractor, point_of_interest, establ..."
4826,North Edgefield Organized,"914 Meridian Street, Nashville","[point_of_interest, establishment]","Pamela G. Murray, MSSW","914 Meridian Street, Nashville","[doctor, health, point_of_interest, establishm...",Hannah Elaine photography,"1006 Meridian Street, Nashville","[point_of_interest, establishment]",McGavock House,"908 Meridian Street, Nashville","[point_of_interest, establishment]",20 Condos and Retail Shops,"Cleveland Street, Nashville","[point_of_interest, establishment]"
4827,31st Ave N & Burch Ave NB,United States,"[transit_station, point_of_interest, establish...",31st Ave N & Long Blvd SB,United States,"[transit_station, point_of_interest, establish...",West End Village,"221 31st Avenue North, Nashville","[real_estate_agency, point_of_interest, establ...",Avoca Apartments,"3108 Long Boulevard, Nashville","[point_of_interest, establishment]","Cooper, Travis & Company PLC","3008 Poston Avenue, Nashville","[accounting, finance, point_of_interest, estab..."
4828,Bucanas Night Club,"3810 Nolensville Pike, Nashville","[night_club, bar, point_of_interest, establish...",Bridal & Formal by RJS,"3806 Nolensville Pike, Nashville","[point_of_interest, clothing_store, store, est...",World Wide Market International Groceries,"3808 Nolensville Pike, Nashville","[grocery_or_supermarket, pharmacy, finance, fo...",Elysian Plaza Shopping Center,Nashville,"[shopping_mall, point_of_interest, establishment]",Quinceanera Dress Store,"3806 Nolensville Pike, Nashville","[point_of_interest, clothing_store, store, est..."

In [19]:
variable = df.join(variable)

In [20]:
variable.head()

,mapped_location,address,results,business_name1,business_vicinity1,business_type1,business_name2,business_vicinity2,business_type2,business_name3,business_vicinity3,business_type3,business_name4,business_vicinity4,business_type4,business_name5,business_vicinity5,business_type5
0,"(36.0685457, -86.6838975)","2045 Antioch Pike, Antioch","[{'business_status': 'OPERATIONAL', 'geometry'...",Los Paisanos,"2045 Antioch Pike, Antioch","[night_club, bar, point_of_interest, establish...",Sun Hair Salon,"2049 Antioch Pike, Antioch","[beauty_salon, hair_care, point_of_interest, e...",Solo Style LLC,"2037 Antioch Pike, Antioch","[clothing_store, point_of_interest, store, est...",Hai Woon Dai,"2051 Antioch Pike, Antioch","[restaurant, food, point_of_interest, establis...","Dr. Babajide A. Bamigboye, MD","2031 Antioch Pike, Antioch","[doctor, health, point_of_interest, establishm..."
1,"(36.211269429469425, -86.6943024067459)","2800 Opryland Dr, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",Best Buy Express Kiosk,"2800 Opryland Dr, Nashville","[point_of_interest, establishment]",Starbucks,Nashville,"[cafe, food, point_of_interest, store, establi...",Imaging USA 2018,"Gaylord Opryland Resort & Convention Center, 2...","[lodging, point_of_interest, establishment]",fiddler,"2800 Opryland Drive, Nashville","[lodging, point_of_interest, establishment]",Swarovski at Gaylord Opryland,"2800 Opryland Drive, Nashville","[jewelry_store, point_of_interest, store, esta..."
2,"(36.1235, -86.79013)","2607 12th Ave S, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",White Bison Coffee,"2607 12th Avenue South, Nashville","[convenience_store, cafe, restaurant, food, po...",Twice Daily,"2607 12th Avenue South, Nashville","[convenience_store, bakery, cafe, liquor_store...",Portland Brew,"2605 12th Avenue South, Nashville","[cafe, food, point_of_interest, establishment]",Alyn Vaughn,"2611 12th Avenue South, Nashville","[point_of_interest, store, establishment]",Blue Monkey Shaved Ice,"2611 12th Avenue South, Nashville","[food, point_of_interest, store, establishment]"
3,"(36.1941628, -86.8313936)","3200 Clarksville Pike, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",TIGERMARKET #203,"3200 Clarksville Highway, Nashville","[gas_station, point_of_interest, establishment]",Clarksville Pike & S Hamilton Rd SB,United States,"[transit_station, point_of_interest, establish...",Shoe Show,"Bordeaux S, 3209 Clarksville Pike C, Nashville","[shoe_store, point_of_interest, store, establi...",Excel Builders of Tennessee,"2107 Buena Vista Pike, Nashville","[general_contractor, real_estate_agency, point...",Campus Rx,"2109 Buena Vista Pike, Nashville","[health, point_of_interest, establishment]"
4,"(36.15843971160494, -86.7880380629013)","20 Grundy St, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",Baldwin Showcase,"Grundy Street, Nashville","[point_of_interest, establishment]",16-Bit Bar+Arcade,"1102 Grundy Street ste b, Nashville","[bar, point_of_interest, establishment]",Christy Weaver,"1102 Grundy Street #A, Nashville","[point_of_interest, establishment]",Pins Mechanical Company,"1102 Grundy Street, Nashville","[bar, point_of_interest, establishment]",Due West Professional Building,"1101 Grundy Street, Nashville","[general_contractor, point_of_interest, establ..."

In [21]:
p='string 1 r'
p.split()

['string', '1', 'r']

In [22]:
variable['address_0'] = [i.split()[0].strip() for i in variable.address]
variable['address_1'] = [i.split()[0].strip() for i in variable.business_vicinity1]
variable['address_2'] = [i.split()[0].strip() for i in variable.business_vicinity2]
variable['address_3'] = [i.split()[0].strip() for i in variable.business_vicinity3]
variable['address_4'] = [i.split()[0].strip() for i in variable.business_vicinity4]
variable['address_5'] = [i.split()[0].strip() for i in variable.business_vicinity5]

In [23]:
variable['address_1'] = variable['address_0']==variable['address_1']
variable['address_2'] = variable['address_0']==variable['address_2']
variable['address_3'] = variable['address_0']==variable['address_3']
variable['address_4'] = variable['address_0']==variable['address_4']
variable['address_5'] = variable['address_0']==variable['address_5']

In [24]:
variable

,mapped_location,address,results,business_name1,business_vicinity1,business_type1,business_name2,business_vicinity2,business_type2,business_name3,...,business_type4,business_name5,business_vicinity5,business_type5,address_0,address_1,address_2,address_3,address_4,address_5
0,"(36.0685457, -86.6838975)","2045 Antioch Pike, Antioch","[{'business_status': 'OPERATIONAL', 'geometry'...",Los Paisanos,"2045 Antioch Pike, Antioch","[night_club, bar, point_of_interest, establish...",Sun Hair Salon,"2049 Antioch Pike, Antioch","[beauty_salon, hair_care, point_of_interest, e...",Solo Style LLC,...,"[restaurant, food, point_of_interest, establis...","Dr. Babajide A. Bamigboye, MD","2031 Antioch Pike, Antioch","[doctor, health, point_of_interest, establishm...",2045,True,False,False,False,False
1,"(36.211269429469425, -86.6943024067459)","2800 Opryland Dr, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",Best Buy Express Kiosk,"2800 Opryland Dr, Nashville","[point_of_interest, establishment]",Starbucks,Nashville,"[cafe, food, point_of_interest, store, establi...",Imaging USA 2018,...,"[lodging, point_of_interest, establishment]",Swarovski at Gaylord Opryland,"2800 Opryland Drive, Nashville","[jewelry_store, point_of_interest, store, esta...",2800,True,False,False,True,True
2,"(36.1235, -86.79013)","2607 12th Ave S, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",White Bison Coffee,"2607 12th Avenue South, Nashville","[convenience_store, cafe, restaurant, food, po...",Twice Daily,"2607 12th Avenue South, Nashville","[convenience_store, bakery, cafe, liquor_store...",Portland Brew,...,"[point_of_interest, store, establishment]",Blue Monkey Shaved Ice,"2611 12th Avenue South, Nashville","[food, point_of_interest, store, establishment]",2607,True,True,False,False,False
3,"(36.1941628, -86.8313936)","3200 Clarksville Pike, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",TIGERMARKET #203,"3200 Clarksville Highway, Nashville","[gas_station, point_of_interest, establishment]",Clarksville Pike & S Hamilton Rd SB,United States,"[transit_station, point_of_interest, establish...",Shoe Show,...,"[general_contractor, real_estate_agency, point...",Campus Rx,"2109 Buena Vista Pike, Nashville","[health, point_of_interest, establishment]",3200,True,False,False,False,False
4,"(36.15843971160494, -86.7880380629013)","20 Grundy St, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",Baldwin Showcase,"Grundy Street, Nashville","[point_of_interest, establishment]",16-Bit Bar+Arcade,"1102 Grundy Street ste b, Nashville","[bar, point_of_interest, establishment]",Christy Weaver,...,"[bar, point_of_interest, establishment]",Due West Professional Building,"1101 Grundy Street, Nashville","[general_contractor, point_of_interest, establ...",20,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4824,"(36.25852, -86.7583)","3638 Dickerson Pike, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",Mid-Tenn Sheet Metal,"3638 Dickerson Pike, Nashville","[general_contractor, point_of_interest, establ...","Keith L. Snead Sr, DC","3638 Dickerson Pike, Nashville","[point_of_interest, establishment]",Bellshire Wellness Center,...,"[electrician, point_of_interest, establishment]",Dr. Speakers Network LLC,"3638 Dickerson Pike STE 203, Nashville","[health, point_of_interest, establishment]",3638,True,True,True,True,True
4825,"(36.153299711602756, -86.7960281)","1722 West End Ave, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",Golden Coast,"1722 West End Avenue, Nashville","[restaurant, food, point_of_interest, establis...",Shabu-Shabu,"1722 West End Avenue, Nashville","[restaurant, food, point_of_interest, establis...",West End Ave & 18th Ave N WB,...,"[point_of_interest, establishment]",Pinaire Roofing,"1720 West End Avenue #530, Nashville","[roofing_contractor, point_of_interest, establ...",1722,True,True,False,False,False
4826,"(36.18837, -86.7676)","1001 Meridian St, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",North Edgefield Organized,"914 Meridian Street, Nashville","[point_of_interest, establishment]","Pamela G. Murray, MSSW","914 Meridian Street, Nashville","[doctor, health, point_of_interest, establishm...",Hannah Elaine photography,...,"[point_of_interest, establishment]",20 Condos and Retail Shops,"Cleveland Street, Nashville","[point_of_interest, establishment]",1001,False,False,False,False,False
4827,"(36.1458305, -86.8167581)","221 31st Ave N, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",31st Ave N & Burch Ave NB,United States,"[transit_station, point_of_interest, establish...",31st Ave N & Long Blvd SB,United States,"[transit_station, point_of_interest, establish...",West End Village,...,"[point_of_interest, establishment]","Cooper, Travis & Company PLC","3008 Poston Avenue, Nashville","[accounting, finance, point_of_interest, estab...",221,False,False,True,False,False
4828,"(36.08778474206125, -86.72961779427743)","3806 Nolensville Pike, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",Bucanas Night Club,"3810 Nolensville Pike, Nashville","[night_club, bar, point_of_interest, establish...",Bridal & Formal by RJS,"3806 Nolensville Pike, Nashville","[point_of_interest, clothing_store, store, est...",World Wide Market International Groceries,...,"[shopping_mall, point_of_interest, establishment]",Quinceanera Dress Store,"3806 Nolensville Pike, Nashville","[point_of_interest, clothing_store, store, est...",3806,False,True,False,False,True

In [25]:
variable['sum'] = variable['address_1'].astype(int) + variable['address_2'].astype(int) + variable['address_3'].astype(int) + variable['address_4'].astype(int) + variable['address_5'].astype(int)

In [26]:
variable['sum'].value_counts()

1    1786
0    1404
2     637
5     412
3     331
4     259
Name: sum, dtype: int64

In [27]:
variable_1s = variable[variable['sum']==1].reset_index(drop=True)

In [28]:
variable_1s.loc[variable_1s.address_1, 'final_name'] = variable_1s.business_name1
variable_1s.loc[variable_1s.address_2, 'final_name'] = variable_1s.business_name2
variable_1s.loc[variable_1s.address_3, 'final_name'] = variable_1s.business_name3
variable_1s.loc[variable_1s.address_4, 'final_name'] = variable_1s.business_name4
variable_1s.loc[variable_1s.address_5, 'final_name'] = variable_1s.business_name5

variable_1s.loc[variable_1s.address_1, 'final_vicinity'] = variable_1s.business_vicinity1
variable_1s.loc[variable_1s.address_2, 'final_vicinity'] = variable_1s.business_vicinity2
variable_1s.loc[variable_1s.address_3, 'final_vicinity'] = variable_1s.business_vicinity3
variable_1s.loc[variable_1s.address_4, 'final_vicinity'] = variable_1s.business_vicinity4
variable_1s.loc[variable_1s.address_5, 'final_vicinity'] = variable_1s.business_vicinity5

variable_1s.loc[variable_1s.address_1, 'final_type'] = variable_1s.business_type1
variable_1s.loc[variable_1s.address_2, 'final_type'] = variable_1s.business_type2
variable_1s.loc[variable_1s.address_3, 'final_type'] = variable_1s.business_type3
variable_1s.loc[variable_1s.address_4, 'final_type'] = variable_1s.business_type4
variable_1s.loc[variable_1s.address_5, 'final_type'] = variable_1s.business_type5

In [29]:
variable_1s['ratio'] = variable_1s.apply(lambda x: fuzz.token_sort_ratio(x['address'], x['final_vicinity']),axis=1)

In [30]:
variable_1s.sort_values('ratio',ascending=False)

,mapped_location,address,results,business_name1,business_vicinity1,business_type1,business_name2,business_vicinity2,business_type2,business_name3,...,address_1,address_2,address_3,address_4,address_5,sum,final_name,final_vicinity,final_type,ratio
0,"(36.0685457, -86.6838975)","2045 Antioch Pike, Antioch","[{'business_status': 'OPERATIONAL', 'geometry'...",Los Paisanos,"2045 Antioch Pike, Antioch","[night_club, bar, point_of_interest, establish...",Sun Hair Salon,"2049 Antioch Pike, Antioch","[beauty_salon, hair_care, point_of_interest, e...",Solo Style LLC,...,True,False,False,False,False,1,Los Paisanos,"2045 Antioch Pike, Antioch","[night_club, bar, point_of_interest, establish...",100
545,"(36.23014, -86.75775)","3105 Dickerson Pike, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",H G Hill Food Stores,"3105 Dickerson Pike, Nashville","[grocery_or_supermarket, supermarket, food, po...",Broadmoor Dr & Hillside Rd WB,United States,"[transit_station, point_of_interest, establish...",SunTrust Mortgage,...,True,False,False,False,False,1,H G Hill Food Stores,"3105 Dickerson Pike, Nashville","[grocery_or_supermarket, supermarket, food, po...",100
287,"(36.0946917, -86.73741369999999)","3715 Nolensville Pike, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",Captain D's,"3715 Nolensville Pike, Nashville","[restaurant, food, point_of_interest, establis...",Tara International Market,"3721 Nolensville Pike, Nashville","[grocery_or_supermarket, food, point_of_intere...",Tara market,...,True,False,False,False,False,1,Captain D's,"3715 Nolensville Pike, Nashville","[restaurant, food, point_of_interest, establis...",100
1344,"(36.16147949999999, -86.7770039)","318 Broadway, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",Tin Roof,"316 Broadway, Nashville","[bar, restaurant, food, point_of_interest, est...",Hideaway Loft,"320 Broadway #202, Nashville","[real_estate_agency, travel_agency, point_of_i...",Boot Barn,...,False,False,True,False,False,1,Boot Barn,"318 Broadway, Nashville","[shoe_store, point_of_interest, clothing_store...",100
1001,"(36.0903259, -86.7323177)","3758 Nolensville Pike, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",ALDI,"3758 Nolensville Pike, Nashville","[grocery_or_supermarket, supermarket, food, po...",Tennessee Snore and Sleep Apnea Centers,"3754 Nolensville Pike, Nashville","[health, point_of_interest, establishment]",Nashville Dental Center,...,True,False,False,False,False,1,ALDI,"3758 Nolensville Pike, Nashville","[grocery_or_supermarket, supermarket, food, po...",100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,"(36.077019198464896, -86.94705514722136)","7613 TN-1, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",Dairy Queen Grill & Chill,"7613 Highway 70 South, Bellevue","[restaurant, food, point_of_interest, store, e...",Walgreens Pharmacy,"7601 Highway 70 South, Bellevue","[pharmacy, health, point_of_interest, store, e...",Redbox,...,True,False,False,False,False,1,Dairy Queen Grill & Chill,"7613 Highway 70 South, Bellevue","[restaurant, food, point_of_interest, store, e...",45
247,"(36.12324446158998, -86.7759098)","2526 Franklin Pike, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",Athens Family Restaurant,"2526 8th Avenue South, Berry Hill","[restaurant, food, point_of_interest, establis...",Craft Vapor,"2528 8th Avenue South, Nashville","[point_of_interest, store, establishment]",Cricket Wireless Authorized Retailer,...,True,False,False,False,False,1,Athens Family Restaurant,"2526 8th Avenue South, Berry Hill","[restaurant, food, point_of_interest, establis...",43
997,"(36.16661129999999, -86.7781258)","Nashville Public Square Park, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",Nashville Public Square Park,"Union St & 3rd Ave N, Nashville","[park, tourist_attraction, point_of_interest, ...",Stand Up Nashville,Nashville,"[point_of_interest, establishment]",Live On The Green,...,False,True,False,False,False,1,Stand Up Nashville,Nashville,"[point_of_interest, establishment]",38
98,"(35.91576187189072, -86.82921350883333)","1299 Murfreesboro Rd, Nan","[{'business_status': 'OPERATIONAL', 'geometry'...",McDonald's,"1299 Tennessee 96 E, Franklin","[cafe, restaurant, food, point_of_interest, st...",Big Shake's Hot Chicken & Fish,"1203 Murfreesboro Road #185, Franklin","[meal_takeaway, restaurant, food, point_of_int...",Big Shake's Nashville Hot Chicken,...,True,False,False,False,False,1,McDonald's,"1299 Tennessee 96 E, Franklin","[cafe, restaurant, food, point_of_interest, st...",38
1321,"(36.26498802975397, -86.71058479696512)","306 TN-6, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",Fifth Third Bank & ATM,"306 North Gallatin Pike North, Madison","[bank, atm, finance, point_of_interest, establ...",Fifth Third Bank ATM,Madison,"[atm, finance, point_of_interest, establishment]",UPS Access Point location,...,True,False,False,False,False,1,Fifth Third Bank & ATM,"306 North Gallatin Pike North, Madison","[bank, atm, finance, point_of_interest, establ...",36

In [31]:
(variable_1s['ratio'] > 80).mean()

0.8449048152295633

In [32]:
(variable_1s['ratio'] > 90).mean() * 1786

1195.0

In [33]:
#variable.to_csv(r'data/Cleaned_google_API_data.csv', index = False)

In [34]:
nville_311 = pd.read_csv('data/hubNashville__311__Service_Requests.csv')
#covid_311 = nville_311.drop(['Request Origin', 'System of Origin ID',
      # 'Contact Type', 'Preferred Language', 'State Issue', 'Parent Request',
     #  'Closed When Created'], axis = 1)

C:\Users\alvin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (17) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [35]:
nville_311 = nville_311.fillna('nan')

In [36]:
covid_311_srt = nville_311[(nville_311['Request Type']=='COVID-19')&(nville_311['Subrequest Type']=='COVID-19 Violations')]

covid_311_rt = covid_311.loc[covid_311['Request Type'].isin(['COVID-19'])]

covid_311_srt = covid_311_rt.loc[covid_311_rt['Subrequest Type'].isin(['COVID-19 Violations'])]

In [37]:
covid_311_srt.drop(columns = ['Additional Subrequest Type'], axis = 1)
covid_311_srt

,Request #,Status,Request Type,Subrequest Type,Additional Subrequest Type,Date / Time Opened,Date / Time Closed,Request Origin,System of Origin ID,Contact Type,...,State Issue,Parent Request,Closed When Created,Address,City,Council District,ZIP,Latitude,Longitude,Mapped Location
1547,444823,Closed,COVID-19,COVID-19 Violations,COVID-19 Violations,08/14/2020 02:38:00 AM,08/14/2020 02:37:15 PM,hubNashville Community,nan,nan,...,False,nan,False,2045 Antioch Pike,ANTIOCH,28,37013,36.0685,-86.6839,"(36.0685457, -86.6838975)"
3380,479965,Closed,COVID-19,COVID-19 Violations,COVID-19 Violations,10/13/2020 11:48:40 AM,10/13/2020 01:48:08 PM,hubNashville Community,nan,nan,...,False,nan,False,2800 Opryland Dr,NASHVILLE,15,37214,36.2113,-86.6943,"(36.211269429469425, -86.6943024067459)"
3661,392927,Closed,COVID-19,COVID-19 Violations,COVID-19 Violations,06/16/2020 12:35:20 AM,06/17/2020 02:28:19 PM,hubNashville Community,nan,nan,...,False,nan,False,2607 12th Ave S,NASHVILLE,18,37204,36.1235,-86.7901,"(36.1235, -86.79013)"
3845,444512,Closed,COVID-19,COVID-19 Violations,COVID-19 Violations,08/13/2020 06:50:31 PM,08/14/2020 02:22:11 PM,hubNashville Community,nan,nan,...,False,nan,False,3200 Clarksville Pike,NASHVILLE,2,37218,36.1942,-86.8314,"(36.1941628, -86.8313936)"
3877,444440,Closed,COVID-19,COVID-19 Violations,COVID-19 Violations,08/13/2020 06:03:09 PM,08/14/2020 02:18:59 PM,hubNashville Community,nan,nan,...,False,nan,False,20 Grundy St,NASHVILLE,19,37203,36.1584,-86.788,"(36.15843971160494, -86.7880380629013)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482606,497610,Closed,COVID-19,COVID-19 Violations,COVID-19 Violations,11/07/2020 01:46:57 AM,11/09/2020 04:35:29 PM,hubNashville Community,nan,nan,...,False,nan,False,3696 Bell Rd,NASHVILLE,13,37214,36.1518,-86.6256,"(36.151847162062914, -86.62563921430471)"
482639,497019,Closed,COVID-19,COVID-19 Violations,COVID-19 Violations,11/06/2020 04:43:39 PM,11/09/2020 04:31:47 PM,Phone,nan,nan,...,False,nan,False,5106 Old Hickory Blvd,NASHVILLE,1,37218,36.2122,-86.92,"(36.21219, -86.92001)"
482663,497616,Closed,COVID-19,COVID-19 Violations,COVID-19 Violations,11/07/2020 02:25:00 AM,11/09/2020 04:22:39 PM,hubNashville Community,nan,nan,...,False,nan,False,8027 E Lamar Alexander Pkwy,nan,nan,nan,35.6798,-83.7367,"(35.67977, -83.7367077)"
482664,497255,Closed,COVID-19,COVID-19 Violations,COVID-19 Violations,11/06/2020 07:19:25 PM,11/09/2020 04:28:53 PM,Phone,nan,nan,...,False,nan,False,440 McMurray Dr,NASHVILLE,27,37211,36.0619,-86.7181,"(36.0619, -86.71806)"
482680,497449,Closed,COVID-19,COVID-19 Violations,COVID-19 Violations,11/06/2020 09:39:27 PM,11/09/2020 04:34:04 PM,Phone,nan,nan,...,False,nan,False,3706 Hillsboro Pike,NASHVILLE,25,37215,36.1098,-86.8109,"(36.1098, -86.81092)"

In [38]:
covid_311_srt['Date / Time Opened'].astype("datetime64[ns]")

1547     2020-08-14 02:38:00
3380     2020-10-13 11:48:40
3661     2020-06-16 00:35:20
3845     2020-08-13 18:50:31
3877     2020-08-13 18:03:09
                 ...
482606   2020-11-07 01:46:57
482639   2020-11-06 16:43:39
482663   2020-11-07 02:25:00
482664   2020-11-06 19:19:25
482680   2020-11-06 21:39:27
Name: Date / Time Opened, Length: 11741, dtype: datetime64[ns]

In [39]:
covid_311_srt['Date / Time Closed'].astype("datetime64[ns]")

1547     2020-08-14 14:37:15
3380     2020-10-13 13:48:08
3661     2020-06-17 14:28:19
3845     2020-08-14 14:22:11
3877     2020-08-14 14:18:59
                 ...
482606   2020-11-09 16:35:29
482639   2020-11-09 16:31:47
482663   2020-11-09 16:22:39
482664   2020-11-09 16:28:53
482680   2020-11-09 16:34:04
Name: Date / Time Closed, Length: 11741, dtype: datetime64[ns]

In [40]:
covid_311_srt.groupby('City')['Council District'].count()

City
ANTIOCH            474
BRENTWOOD           50
GOODLETTSVILLE     207
HERMITAGE          431
JOELTON             43
LA VERGNE            1
LAVERGNE             9
MADISON            587
NASHVILLE         8713
NOLENSVILLE          5
Nashville            1
OLD HICKORY        204
WHITES CREEK        27
nan                989
Name: Council District, dtype: int64

In [41]:
covid_311_srt['City'] = covid_311_srt['City'].str.title().fillna('.')

<ipython-input-41-bef5d98d065a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  covid_311_srt['City'] = covid_311_srt['City'].str.title().fillna('.')

In [42]:
covid_311_srt['address_city'] = covid_311_srt['Address']  + ', ' + covid_311_srt['City']

<ipython-input-42-08937caf5814>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  covid_311_srt['address_city'] = covid_311_srt['Address']  + ', ' + covid_311_srt['City']

In [43]:
Covid_311_counts = pd.DataFrame(covid_311_srt.groupby('address_city')['Request #'].count()).reset_index()
Covid_311_counts

                                  address_city  Request #
0              1 Averitt Express Dr, Nashville          1
1                1 Bridgestone Park, Nashville          1
2                         1 CLUB DR, Nashville          1
3                           1 Cadillac Dr, Nan          1
4                         1 Club Dr, Nashville         10
...                                        ...        ...
4995                              nan, Madison          3
4996                                  nan, Nan        279
4997                            nan, Nashville         85
4998       nolensville rd and thompson ln, Nan          1
4999  the broken spoke nashville tn, Nashville          1

[5000 rows x 2 columns]

In [60]:
Merged_google_Covid_cases = pd.merge(variable_1s,Covid_311_counts, left_on='address', right_on='address_city', how='left')
Merged_google_Covid_cases

,mapped_location,address,results,business_name1,business_vicinity1,business_type1,business_name2,business_vicinity2,business_type2,business_name3,...,address_3,address_4,address_5,sum,final_name,final_vicinity,final_type,ratio,address_city,Request #
0,"(36.0685457, -86.6838975)","2045 Antioch Pike, Antioch","[{'business_status': 'OPERATIONAL', 'geometry'...",Los Paisanos,"2045 Antioch Pike, Antioch","[night_club, bar, point_of_interest, establish...",Sun Hair Salon,"2049 Antioch Pike, Antioch","[beauty_salon, hair_care, point_of_interest, e...",Solo Style LLC,...,False,False,False,1,Los Paisanos,"2045 Antioch Pike, Antioch","[night_club, bar, point_of_interest, establish...",100,"2045 Antioch Pike, Antioch",8
1,"(36.1941628, -86.8313936)","3200 Clarksville Pike, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",TIGERMARKET #203,"3200 Clarksville Highway, Nashville","[gas_station, point_of_interest, establishment]",Clarksville Pike & S Hamilton Rd SB,United States,"[transit_station, point_of_interest, establish...",Shoe Show,...,False,False,False,1,TIGERMARKET #203,"3200 Clarksville Highway, Nashville","[gas_station, point_of_interest, establishment]",80,"3200 Clarksville Pike, Nashville",1
2,"(36.16502, -86.78968)","130 LifeWay Plaza, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",Frankie Pierce Park,"130 LifeWay Plaza, Nashville","[park, point_of_interest, establishment]",Frankie Pierce Park,"Frankie Pierce Park, 130 LifeWay Plaza, Nashville","[park, point_of_interest, establishment]",Rukus Cycling Studios,...,False,False,False,1,Frankie Pierce Park,"130 LifeWay Plaza, Nashville","[park, point_of_interest, establishment]",100,"130 LifeWay Plaza, Nashville",4
3,"(36.2328375, -86.75830260000001)","3131 Dickerson Rd, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",Wendy's,"3131 Dickerson Road, Nashville","[restaurant, food, point_of_interest, establis...",Maplewood Trace & Dickerson PK WB,United States,"[transit_station, point_of_interest, establish...",Church's Chicken,...,False,False,False,1,Wendy's,"3131 Dickerson Road, Nashville","[restaurant, food, point_of_interest, establis...",96,"3131 Dickerson Rd, Nashville",4
4,"(36.1105402, -86.7564862)","651 Thompson Ln, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",Tennessee Glass Co,"651 Thompson Lane, Nashville","[furniture_store, home_goods_store, general_co...",Nadeau - Furniture With a Soul,"647 Thompson Lane, Nashville","[furniture_store, home_goods_store, point_of_i...",Bank of America ATM,...,False,False,False,1,Tennessee Glass Co,"651 Thompson Lane, Nashville","[furniture_store, home_goods_store, general_co...",96,"651 Thompson Ln, Nashville",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1781,"(36.1445039, -86.8138932)","2914 West End Ave, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",Bombay Palace,"2912 West End Avenue, Nashville","[restaurant, food, point_of_interest, establis...",China Dragon,"2914 West End Avenue, Nashville","[restaurant, food, point_of_interest, establis...",Dead Ahead Tattoo Co.,...,False,False,False,1,China Dragon,"2914 West End Avenue, Nashville","[restaurant, food, point_of_interest, establis...",95,"2914 West End Ave, Nashville",1
1782,"(36.15236331160235, -86.84059105)","4408 TN-24, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",M.L.Rose Craft Beer & Burgers - Sylvan Park,"4408 Charlotte Avenue, Nashville","[bar, restaurant, food, point_of_interest, est...",Live Love Lead,"4501 Charlotte Avenue, Nashville","[point_of_interest, establishment]",Glitz Nashville,...,False,False,False,1,M.L.Rose Craft Beer & Burgers - Sylvan Park,"4408 Charlotte Avenue, Nashville","[bar, restaurant, food, point_of_interest, est...",55,"4408 TN-24, Nashville",1
1783,"(36.1946271, -86.6234053)","3918 Lebanon Pike, Hermitage","[{'business_status': 'OPERATIONAL', 'geometry'...",Super Wok,"3918 Lebanon Pike, Hermitage","[meal_delivery, restaurant, food, point_of_int...",MoneyGram,"3922 Lebanon Pike, Hermitage","[finance, point_of_interest, establishment]",Mexicali Market,...,False,False,False,1,Super Wok,"3918 Lebanon Pike, Hermitage","[meal_delivery, restaurant, food, point_of_int...",100,"3918 Lebanon Pike, Hermitage",1
1784,"(36.07927, -86.72747)","420 Harding Pl, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",Patel Brothers,"420 Harding Place, Nashville","[supermarket, grocery_or_supermarket, food, po...",Harding Pl & Nolensville Pike WB,United States,"[transit_station, point_of_interest, establish...",Advance Financial,...,False,False,False,1,Patel Brothers,"420 Harding Place, Nashville","[supermarket, grocery_or_supermarket, food, po...",94,"420 Harding Pl, Nashville",1
1785,"(36.1458305, -86.8167581)","221 31st Ave N, Nashville","[{'business_status': 'OPERATIONAL', 'geometry'...",31st Ave N & Burch Ave NB,United States,"[transit_station, point_of_interest, establish...",31st Ave N & Long Blvd SB,United States,"[transit_station, point_of_interest, establish...",West End Village,...,True,False,False,1,West End Village,"221 31st Avenue North, Nashville","[real_estate_agency, point_of_interest, establ...",84,"221 31st Ave N, Nashville",1

In [61]:
Merged_google_Covid_cases.to_csv('Merged_google_Covid_cases.csv')

In [45]:
variable['business_vicinity1'].str.contains('2045 Antioch Pike')

0        True
1       False
2       False
3       False
4       False
        ...
4824    False
4825    False
4826    False
4827    False
4828    False
Name: business_vicinity1, Length: 4829, dtype: bool

In [46]:
covid_311_srt.Address.iloc[0]

'2045 Antioch Pike'

In [47]:
variable[['business_vicinity1','business_vicinity2','business_vicinity3','business_vicinity4','business_vicinity5']].applymap(lambda x:'2045 Antioch Pike' in x)

,business_vicinity1,business_vicinity2,business_vicinity3,business_vicinity4,business_vicinity5
0,True,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
...,...,...,...,...,...
4824,False,False,False,False,False
4825,False,False,False,False,False
4826,False,False,False,False,False
4827,False,False,False,False,False
4828,False,False,False,False,False

In [48]:
row = variable.iloc[0]
row

mapped_location                               (36.0685457, -86.6838975)
address                                      2045 Antioch Pike, Antioch
results               [{'business_status': 'OPERATIONAL', 'geometry'...
business_name1                                             Los Paisanos
business_vicinity1                           2045 Antioch Pike, Antioch
business_type1        [night_club, bar, point_of_interest, establish...
business_name2                                           Sun Hair Salon
business_vicinity2                           2049 Antioch Pike, Antioch
business_type2        [beauty_salon, hair_care, point_of_interest, e...
business_name3                                           Solo Style LLC
business_vicinity3                           2037 Antioch Pike, Antioch
business_type3        [clothing_store, point_of_interest, store, est...
business_name4                                             Hai Woon Dai
business_vicinity4                           2051 Antioch Pike, Antioch
business_type4        [restaurant, food, point_of_interest, establis...
business_name5                            Dr. Babajide A. Bamigboye, MD
business_vicinity5                           2031 Antioch Pike, Antioch
business_type5        [doctor, health, point_of_interest, establishm...
address_0                                                          2045
address_1                                                          True
address_2                                                         False
address_3                                                         False
address_4                                                         False
address_5                                                         False
sum                                                                   1
Name: 0, dtype: object

In [49]:
def find_row_type(row):
    if row['address'] == row['business_vicinity1']:
        return row['business_type1']
    if row['address'] == row['business_vicinity2']:
        return row['business_type2']
    if row['address'] == row['business_vicinity3']:
        return row['business_type3']
    if row['address'] == row['business_vicinity4']:
        return row['business_type4']
    if row['address'] == row['business_vicinity5']:
        return row['business_type5']

In [50]:
def find_row_name(row):
    if row['address'] == row['business_vicinity1']:
        return row['business_name1']
    if row['address'] == row['business_vicinity2']:
        return row['business_name2']
    if row['address'] == row['business_vicinity3']:
        return row['business_name3']
    if row['address'] == row['business_vicinity4']:
        return row['business_name4']
    if row['address'] == row['business_vicinity5']:
        return row['business_name5']

In [51]:
area_types = variable.apply(find_row_type,axis=1)
area_types

0       [night_club, bar, point_of_interest, establish...
1                      [point_of_interest, establishment]
2                                                    None
3                                                    None
4                                                    None
                              ...
4824    [general_contractor, point_of_interest, establ...
4825                                                 None
4826                                                 None
4827                                                 None
4828    [point_of_interest, clothing_store, store, est...
Length: 4829, dtype: object

In [52]:
area_types.count()

775

In [53]:
area_names = variable.apply(find_row_name,axis=1)
area_names

0                 Los Paisanos
1       Best Buy Express Kiosk
2                         None
3                         None
4                         None
                 ...
4824      Mid-Tenn Sheet Metal
4825                      None
4826                      None
4827                      None
4828    Bridal & Formal by RJS
Length: 4829, dtype: object

In [54]:
def find_fuzzy_row_type(row):
    i=95
    if fuzz.ratio(row['address'],row['business_vicinity1']) >= i:
        return row['business_type1']
    if fuzz.ratio(row['address'],row['business_vicinity2']) >= i:
        return row['business_type2']
    if fuzz.ratio(row['address'],row['business_vicinity3']) >= i:
        return row['business_type3']
    if fuzz.ratio(row['address'],row['business_vicinity4']) >= i:
        return row['business_type4']
    if fuzz.ratio(row['address'],row['business_vicinity5']) >= i:
        return row['business_type5']

In [55]:
def find_fuzzy_row_name(row):
    i=85
    if fuzz.ratio(row['address'],row['business_vicinity1']) >= i:
        return row['business_name1']
    if fuzz.ratio(row['address'],row['business_vicinity2']) >= i:
        return row['business_name2']
    if fuzz.ratio(row['address'],row['business_vicinity3']) >= i:
        return row['business_name3']
    if fuzz.ratio(row['address'],row['business_vicinity4']) >= i:
        return row['business_name4']
    if fuzz.ratio(row['address'],row['business_vicinity5']) >= i:
        return row['business_name5']

In [56]:
fuzzy_area_type= variable.apply(find_fuzzy_row_type,axis=1)
fuzzy_area_type

0       [night_club, bar, point_of_interest, establish...
1                      [point_of_interest, establishment]
2                                                    None
3                                                    None
4                                                    None
                              ...
4824    [general_contractor, point_of_interest, establ...
4825    [restaurant, food, point_of_interest, establis...
4826                                                 None
4827                                                 None
4828    [night_club, bar, point_of_interest, establish...
Length: 4829, dtype: object

In [57]:
fuzzy_area_type.count()

1693

In [58]:
fuzzy_area_names= variable.apply(find_fuzzy_row_name,axis=1)
fuzzy_area_names

0                    Los Paisanos
1          Best Buy Express Kiosk
2              White Bison Coffee
3                TIGERMARKET #203
4                Baldwin Showcase
                  ...
4824         Mid-Tenn Sheet Metal
4825                 Golden Coast
4826    Hannah Elaine photography
4827             West End Village
4828           Bucanas Night Club
Length: 4829, dtype: object

In [59]:
fuzzy_area_names.count()

3457

Rules
If not Exact match Fail
If not only one match Fail